version: "3.9"
services:
  postgresql_14:
    image: postgres:14.5-alpine
    container_name: gridbase_postgresql_14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
  postgresql_13:
    image: postgres:13.8-alpine
    container_name: gridbase_postgresql_13
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=admin
  postgresql_12:
    image: postgres:12.12-alpine
    container_name: gridbase_postgresql_12
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_PASSWORD=admin
  postgresql_11:
    image: postgres:11.17-alpine
    container_name: gridbase_postgresql_11
    ports:
      - "5429:5432"
    environment:
      - POSTGRES_PASSWORD=admin
  postgresql_10:
    image: postgres:10.22-alpine
    container_name: gridbase_postgresql_10
    ports:
      - "5428:5432"
    environment:
      - POSTGRES_PASSWORD=admin
